import { QuestionnaireQuestion, CareerProfile, StudentSubmissionDetail } from './types';

export const questionnaireQuestions: QuestionnaireQuestion[] = [
  {
    id: 'q1',
    category: 'Favorite Activities',
    question: 'Which of these activities sounds most fun to you?',
    subtitle: 'Choose what you enjoy doing the most.',
    options: [
      {
        id: 'q1-a',
        label: 'Building things, tinkering with gadgets, or solving math puzzles.',
        dimensionWeights: { analytical: 4, technical: 5, research: 1, creative: 0, leadership: 0, communication: 0 },
      },
      {
        id: 'q1-b',
        label: 'Helping sick people, caring for animals, or studying nature.',
        dimensionWeights: { analytical: 2, technical: 0, research: 5, creative: 0, leadership: 0, communication: 1 },
      },
      {
        id: 'q1-c',
        label: 'Speaking in front of people, reading books, or writing stories.',
        dimensionWeights: { analytical: 0, technical: 0, research: 1, creative: 1, leadership: 4, communication: 5 },
      },
      {
        id: 'q1-d',
        label: 'Drawing pictures, painting, or designing creative art.',
        dimensionWeights: { analytical: 0, technical: 1, research: 0, creative: 5, leadership: 0, communication: 2 },
      },
    ],
  },
  {
    id: 'q2',
    category: 'School Subjects',
    question: 'Which subject in school do you enjoy the most?',
    subtitle: 'Think about your favorite class.',
    options: [
      {
        id: 'q2-a',
        label: 'Mathematics and Computer Science.',
        dimensionWeights: { analytical: 5, technical: 4, research: 1, creative: 0, leadership: 0, communication: 0 },
      },
      {
        id: 'q2-b',
        label: 'Biology and Science experiments.',
        dimensionWeights: { analytical: 2, technical: 1, research: 5, creative: 0, leadership: 0, communication: 0 },
      },
      {
        id: 'q2-c',
        label: 'English, History, and Social Studies.',
        dimensionWeights: { analytical: 0, technical: 0, research: 2, creative: 1, leadership: 3, communication: 5 },
      },
      {
        id: 'q2-d',
        label: 'Art, Craft, and Design.',
        dimensionWeights: { analytical: 0, technical: 0, research: 0, creative: 5, leadership: 1, communication: 2 },
      },
    ],
  },
  {
    id: 'q3',
    category: 'Teamwork',
    question: 'When working on a school project with friends, what role do you like to take?',
    subtitle: 'How do you help out best in a group?',
    options: [
      {
        id: 'q3-a',
        label: 'Building the project model or figuring out how it works.',
        dimensionWeights: { analytical: 3, technical: 5, research: 1, creative: 0, leadership: 1, communication: 0 },
      },
      {
        id: 'q3-b',
        label: 'Finding facts, reading books, and gathering information.',
        dimensionWeights: { analytical: 3, technical: 0, research: 5, creative: 0, leadership: 0, communication: 1 },
      },
      {
        id: 'q3-c',
        label: 'Leading the team and presenting our project to the class.',
        dimensionWeights: { analytical: 1, technical: 0, research: 0, creative: 1, leadership: 5, communication: 4 },
      },
      {
        id: 'q3-d',
        label: 'Making colorful posters, slides, and decorating our project.',
        dimensionWeights: { analytical: 0, technical: 0, research: 0, creative: 5, leadership: 1, communication: 3 },
      },
    ],
  },
  {
    id: 'q4',
    category: 'Dream Field Trip',
    question: 'If your school goes on a field trip, where would you choose to go?',
    subtitle: 'Pick your dream destination.',
    options: [
      {
        id: 'q4-a',
        label: 'A High-Tech Robotics & Space Center.',
        dimensionWeights: { analytical: 3, technical: 5, research: 2, creative: 0, leadership: 0, communication: 0 },
      },
      {
        id: 'q4-b',
        label: 'A Medical Research Lab or Wildlife Nature Reserve.',
        dimensionWeights: { analytical: 2, technical: 0, research: 5, creative: 0, leadership: 0, communication: 1 },
      },
      {
        id: 'q4-c',
        label: 'A City Law Court, Parliament, or Debate Center.',
        dimensionWeights: { analytical: 1, technical: 0, research: 1, creative: 0, leadership: 4, communication: 5 },
      },
      {
        id: 'q4-d',
        label: 'An Art Studio & Creative Design Museum.',
        dimensionWeights: { analytical: 0, technical: 1, research: 0, creative: 5, leadership: 0, communication: 2 },
      },
    ],
  },
  {
    id: 'q5',
    category: 'Future Goals',
    question: 'What would you love to do when you grow up?',
    subtitle: 'Choose your dream goal.',
    options: [
      {
        id: 'q5-a',
        label: 'Invent new machines, software, or build strong bridges.',
        dimensionWeights: { analytical: 4, technical: 5, research: 1, creative: 1, leadership: 0, communication: 0 },
      },
      {
        id: 'q5-b',
        label: 'Cure illnesses, save lives, and help people stay healthy.',
        dimensionWeights: { analytical: 2, technical: 0, research: 5, creative: 0, leadership: 1, communication: 2 },
      },
      {
        id: 'q5-c',
        label: 'Stand up for fairness, teach students, or write inspiring books.',
        dimensionWeights: { analytical: 0, technical: 0, research: 1, creative: 2, leadership: 4, communication: 5 },
      },
      {
        id: 'q5-d',
        label: 'Create beautiful paintings, digital graphics, or fashion designs.',
        dimensionWeights: { analytical: 0, technical: 1, research: 0, creative: 5, leadership: 0, communication: 2 },
      },
    ],
  },
];

export const careerCatalog: CareerProfile[] = [
  {
    id: 'career-engineer',
    title: 'Engineer',
    category: 'Engineering & Technology',
    badge: 'Popular Choice',
    description: 'Design machines, build structures, create computer software, and solve technical problems that help society.',
    matchPercentage: 95,
    salaryRange: 'High Growth Field',
    growthOutlook: 'Very High Demand',
    requiredSkills: ['Problem Solving', 'Math & Logic', 'Coding & Building', 'Creativity'],
    recommendedRoadmap: [
      'Join school STEM and robotics clubs',
      'Practice math and computer programming basics',
      'Build simple science & engineering projects',
      'Participate in school science fairs',
    ],
    primaryDimension: 'technical',
    accentColor: '#0ea5e9',
  },
  {
    id: 'career-doctor',
    title: 'Doctor',
    category: 'Healthcare & Medicine',
    badge: 'Healthcare Focus',
    description: 'Help people stay healthy, treat illnesses, conduct medical research, and save lives in hospitals and clinics.',
    matchPercentage: 94,
    salaryRange: 'High Impact Field',
    growthOutlook: 'Essential Role',
    requiredSkills: ['Biology & Health', 'Empathy & Care', 'Problem Solving', 'Observation'],
    recommendedRoadmap: [
      'Study life sciences and biology topics',
      'Participate in first-aid and health awareness workshops',
      'Read books on human biology and anatomy',
      'Volunteer for community health drives',
    ],
    primaryDimension: 'research',
    accentColor: '#10b981',
  },
  {
    id: 'career-lawyer',
    title: 'Lawyer',
    category: 'Law, Justice & Civics',
    badge: 'Leadership Choice',
    description: 'Protect human rights, uphold justice, present convincing arguments, and help solve disputes in court.',
    matchPercentage: 92,
    salaryRange: 'High Impact Field',
    growthOutlook: 'Steady Demand',
    requiredSkills: ['Public Speaking', 'Critical Thinking', 'Debate & Logic', 'Reading & Research'],
    recommendedRoadmap: [
      'Join school debate & model UN clubs',
      'Read books on history and civics',
      'Practice public speaking and essay writing',
      'Follow current events and community news',
    ],
    primaryDimension: 'communication',
    accentColor: '#8b5cf6',
  },
  {
    id: 'career-scientist',
    title: 'Scientist',
    category: 'Science & Research',
    badge: 'Explorer Choice',
    description: 'Conduct exciting experiments, discover new scientific facts, study nature, and invent new technologies.',
    matchPercentage: 90,
    salaryRange: 'High Growth Field',
    growthOutlook: 'High Demand',
    requiredSkills: ['Scientific Research', 'Curiosity', 'Data Analysis', 'Observation'],
    recommendedRoadmap: [
      'Conduct chemistry & physics science experiments',
      'Read science magazines and nature books',
      'Visit science museums and planetariums',
      'Enter school research competitions',
    ],
    primaryDimension: 'analytical',
    accentColor: '#f59e0b',
  },
  {
    id: 'career-teacher',
    title: 'Teacher',
    category: 'Education & Mentorship',
    badge: 'Mentorship Choice',
    description: 'Inspire young minds, share knowledge, guide students, and help shape the leaders of tomorrow.',
    matchPercentage: 89,
    salaryRange: 'High Impact Field',
    growthOutlook: 'Essential Role',
    requiredSkills: ['Communication', 'Patience', 'Leadership', 'Subject Mastery'],
    recommendedRoadmap: [
      'Help classmates with peer tutoring',
      'Practice public speaking and presenting',
      'Read widely across various school subjects',
      'Participate in youth mentoring programs',
    ],
    primaryDimension: 'leadership',
    accentColor: '#f97316',
  },
  {
    id: 'career-artist',
    title: 'Artist & Designer',
    category: 'Creative Arts & Media',
    badge: 'Creative Focus',
    description: 'Create beautiful paintings, digital graphics, illustrations, and visual designs that inspire people.',
    matchPercentage: 91,
    salaryRange: 'Creative Field',
    growthOutlook: 'High Demand',
    requiredSkills: ['Drawing & Sketching', 'Color Theory', 'Digital Arts', 'Imagination'],
    recommendedRoadmap: [
      'Practice drawing, painting, and digital sketching',
      'Build a portfolio of school art projects',
      'Learn digital design tools (Canva, Photoshop)',
      'Participate in art exhibitions and contests',
    ],
    primaryDimension: 'creative',
    accentColor: '#e11d48',
  },
  {
    id: 'career-architect',
    title: 'Architect',
    category: 'Architecture & Design',
    badge: 'Builder Choice',
    description: 'Design beautiful buildings, eco-friendly homes, modern bridges, and smart city spaces.',
    matchPercentage: 88,
    salaryRange: 'High Growth Field',
    growthOutlook: 'Steady Demand',
    requiredSkills: ['3D Design', 'Geometry & Math', 'Creativity', 'Spatial Thinking'],
    recommendedRoadmap: [
      'Practice 3D sketching and model building',
      'Learn basic geometry and spatial design',
      'Explore architectural drawing apps',
      'Study historic and modern building designs',
    ],
    primaryDimension: 'analytical',
    accentColor: '#6366f1',
  },
  {
    id: 'career-astronaut',
    title: 'Astronaut',
    category: 'Space & Exploration',
    badge: 'Inspiring Choice',
    description: 'Travel into outer space, pilot space stations, study stars and planets, and explore the universe.',
    matchPercentage: 87,
    salaryRange: 'Futuristic Field',
    growthOutlook: 'Expanding Horizon',
    requiredSkills: ['Physics & Math', 'Physical Fitness', 'Problem Solving', 'Teamwork'],
    recommendedRoadmap: [
      'Study astronomy and space physics',
      'Participate in science clubs and physical sports',
      'Build rocket & flight simulator models',
      'Visit space centers and planetariums',
    ],
    primaryDimension: 'technical',
    accentColor: '#06b6d4',
  },
];

export const sampleInitialSubmissions: StudentSubmissionDetail[] = [];
